name: GitHub Actions Demo
on: [push]

env:
  GITHUB_EVENT_BEFORE: ${{ github.event.before }}
  GITHUB_EVENT_AFTER: ${{ github.event.after }}

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "master"
          fetch-depth: "0"
      - name: Run jq
        id: getCoreComponentLibraryPaths
        uses: sergeysova/jq-action@v2
        with:
          cmd: "jq .version package.json -r"
      - name: Show my version
        run: 'echo "version ${{ steps.version.outputs.value }}"'
      - run: echo "the before ${{ env.GITHUB_EVENT_BEFORE }}"
      - run: echo "the after ${{ env.GITHUB_EVENT_AFTER }}"
      - run: chmod +x "${GITHUB_WORKSPACE}/.github/test.sh"
      - run: ${GITHUB_WORKSPACE}/.github/test.sh
