name: GitHub Actions Demo
on:
  push:
    branches:
      - actions-test

env:
  GITHUB_EVENT_BEFORE: ${{ github.event.before }}
  GITHUB_EVENT_AFTER: ${{ github.event.after }}

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "master"
          fetch-depth: "0"
      - run: ls
      - run: ${GITHUB_WORKSPACE} ls
      - run: echo "the before ${{ env.GITHUB_EVENT_BEFORE }}"
      - run: echo "the after ${{ env.GITHUB_EVENT_AFTER }}"
      - run: chmod +x "${GITHUB_WORKSPACE}/.github/test.sh"
      - run: ${GITHUB_WORKSPACE}/.github/test.sh
