name: GitHub Actions Demo
on: [push]

env:
  GITHUB_EVENT_BEFORE: ${{ github.event.before }}
  GITHUB_EVENT_AFTER: ${{ github.event.after }}

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "the before ${{ env.GITHUB_EVENT_BEFORE }}"
      - run: echo "the after ${{ env.GITHUB_EVENT_AFTER }}"
      - run: pwd
      # - run: cd ${GITHUB_WORKSPACE}/.github/
      - run: ls -la
      - run: chmod +x "${GITHUB_WORKSPACE}/.github/test.sh"
      - run: ${GITHUB_WORKSPACE}/.github/test.sh
